language: groovy
script: bash ci-build.sh
addons:
  apt:
    packages:
    - pandoc
    - make
    - zip
    - unzip
deploy:
  - provider: script
    script: bash ci-deploy.sh
    skip_cleanup: true
    on:
      condition: $TRAVIS_BRANCH =~ ^[[:digit:]].*x$ || $TRAVIS_TAG